# Server configuations
server:
  host: "localhost" 
  port: 8080

# MySQL Database configuations
database:
  user: "dbuser" # DB User name
  pass: "Ej3yj/ru8@" # DB User password
  dbname: "UserDB" # DB name
  host: "127.0.0.1" # DB Server's host 
  port: 3306 # DB Server's port