# Server configuations
server:
  host: "localhost" 
  port: 8080

# MySQL Database configuations
database:
  user: "dbuser" # DB User name
  pass: "8*S+0nCxS9/ngYjczCaq" # DB User password
  dbname: "UserDB" # DB name
  host: "db" # DB Server's host 
  port: 3306 # DB Server's port