// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kabuto412rock/microblog/config"
	"github.com/kabuto412rock/microblog/controller"
	"github.com/kabuto412rock/microblog/internal"
)

// Injectors from wire.go:

func InitalizeServer() *internal.Server {
	configConfig := config.ReadConfig()
	env := controller.NewEnv(configConfig)
	server := internal.NewServer(configConfig, env)
	return server
}
